# Generated by Django 6.1 on 2026-08-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game_State',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_state', models.CharField(choices=[('a', 'active'), ('w', 'won'), ('l', 'lost')], default='a', max_length=1)),
                ('guessed_word', models.CharField(default='', max_length=50)),
                ('guessed_letters', models.CharField(default='', max_length=26)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('max_incorrect_guesses', models.IntegerField(default=1)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangman_app.word')),
            ],
        ),
    ]
